print('======= DESAFIO 04 =======')
a = input('Digite qualquer coisa: ')
print('Seu tipo primitivo é {}'.format(type(a)))
print('Número? {}'.format(a.isnumeric()))
print('Letra? {}'.format(a.isalpha()))
print('Alfanumérico? {}'.format(a.isalnum()))
print('MAIÚSCULO? {}'.format(a.isupper()))
print('minúsculo? {}'.format(a.islower()))
print('São espaços? {}'.format(a.isspace()))
print('Primeira letra Maiúscula/Capitalizada? {}'.format(a.istitle()))
